### PR TITLE
issue#1539 participant status bug

### LINKED ISSUE #1539: Participation Status Flag Bug
Placeholder for requirements.

In Nov/Dec release, @kmazzilli identified an issue on the SMDB (see original github issue thread here: https://github.com/episphere/connect/issues/1437#issuecomment-3632909346/) where if a pt already has an activity refused (e.g. refused all future activities) and then has a suspended contact entered for them in the SMDB, the participation status' variable' is reverted back to 'no refusal'.

We will want to revisit the code and discuss with @FrogGirl1123 intended outcome before finalizing requirements.

Will not be included in Jan Release.

### PR DESCRIPTION
**Pull request by Gbarra9**
A pull request for issue#1539.

- https://github.com/episphere/connect/issues/1539

Bug:
- A participant with a previous participation status has their contact suspended. This results in the previous `912301837 (participation status)` to change to `208325815 (no refusal)`.

Code Change:
- Removed line inside `hasPriorParticipationStatus` conditional block that reverted participation status's value to no refusal upon suspend contact.
- Added check to prevent prior status-scoring participation status from updating timestamp

### CODE REVIEW

**Review by bransteitterbr — APPROVED** [review]

File: src/participantWithdrawalForm.js [hunk 1]
```diff
@@ -864,11 +866,13 @@ export const processRefusalWithdrawalResponses = async (selectedReasonsForWithdr
                                             "Destroy Data": 5,
                                             "Deceased": 6, }
         const participant = participantState.getParticipant();
-        let prevParticipantStatusSelection = fieldMapping[participant[fieldMapping.participationStatus]]
-        prevParticipantStatusSelection = prevParticipantStatusScore[prevParticipantStatusSelection]
-        highestStatus.push(parseInt(prevParticipantStatusSelection))
+        let prevParticipantStatusSelection = fieldMapping[participant[fieldMapping.participationStatus]];
+
+        if (hasStatusSelection) {
+            prevParticipantStatusSelection = prevParticipantStatusScore[prevParticipantStatusSelection];
```
Comment (we-ai) [inline src/participantWithdrawalForm.js:872]: Small thing. Same variable used for different data types.
The status in line 869 is a string, and it's an integer in line 872. May not need to use `parstInt` since it's an integer already.

**Review by we-ai — APPROVED** [review]
Looks good.
